/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t *pPortAOutReg = (uint32_t*)0x40020014;

	// Enable the clock
	*pClkCtrlReg |= 0x01;

	// Configure mode of IO Pin as output
	// Clear 10 and 11 bit position
	// Using 3 as binary value of 3 is 11
//	*pPortAModeReg &= 0xFFFFF3FF;
	*pPortAModeReg &= ~(3 << 10);
	// Set the 10th bit
	*pPortAModeReg |= (1 << 10);

	while (1) {
		// Set 5th bit of output data register to make IO pin 5 HIGH
		*pPortAOutReg |= (1 << 5);

		for (uint32_t i = 0; i < 200000; ++i);

		*pPortAOutReg &= ~(1 << 5);

		for (uint32_t i = 0; i < 200000; ++i);
	}
}

