/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay() {
	for (uint32_t i = 0; i < 300000; ++i);
}

int main(void)
{
	// peripheral register pointers
	uint32_t volatile *const pGPIODModeReg  =  (uint32_t*)0x40020C00;
	uint32_t volatile *const pInputDataReg  =  (uint32_t*)(0x40020C00 + 0x10);
	uint32_t volatile *const pOutputDataReg =  (uint32_t*)(0x40020C00 + 0x14);
	uint32_t volatile *const pClkCtrlReg    =  (uint32_t*)(0x40023800 + 0x30);
	uint32_t volatile *const pPullUpDownReg =  (uint32_t*)(0x40020C00 + 0x0C);

	// Enable Clock for GPIOD peripheral
	*pClkCtrlReg |= (1 << 3);

	// Configure PD0, PD1, PD2, PD3 as output (rows)
	*pGPIODModeReg &= ~(0xFF);
	*pGPIODModeReg |= 0x55;

	// Configure PD8, PD9, PD10 as input (columns)
	*pGPIODModeReg &= ~(0x3F << 16);

	// Enable pull up resistors for PD8, PD9, PD10 (columns)
	*pPullUpDownReg &= ~(0x3F << 16);
	*pPullUpDownReg |= (0x15 << 16);

	while (1) {
		// Make all rows high
		*pOutputDataReg |= (0x0f);

		// Make r1 low (PD0)
		*pOutputDataReg &= ~(1 << 0);

		// Scan the columns
		// Check PD8 -> C1
		if (!(*pInputDataReg & (1 << 8))) {
			delay();
			printf("1\n");
		}
		// Check PD9 -> C2
		if (!(*pInputDataReg & (1 << 9))) {
			delay();
			printf("2\n");
		}
		// Check PD10 -> C3
		if (!(*pInputDataReg & (1 << 10))) {
			delay();
			printf("3\n");
		}

		// Make all rows high
		*pOutputDataReg |= (0x0f);
		// Make r2 low (PD1)
		*pOutputDataReg &= ~(1 << 1);

		// Scan the columns
		// Check PD8 -> C1
		if (!(*pInputDataReg & (1 << 8))) {
			delay();
			printf("4\n");
		}
		// Check PD9 -> C2
		if (!(*pInputDataReg & (1 << 9))) {
			delay();
			printf("5\n");
		}
		// Check PD10 -> C3
		if (!(*pInputDataReg & (1 << 10))) {
			delay();
			printf("6\n");
		}

		// Make all rows high
		*pOutputDataReg |= (0x0f);
		// Make r3 low (PD2)
		*pOutputDataReg &= ~(1 << 2);

		// Scan the columns
		// Check PD8 -> C1
		if (!(*pInputDataReg & (1 << 8))) {
			delay();
			printf("7\n");
		}
		// Check PD9 -> C2
		if (!(*pInputDataReg & (1 << 9))) {
			delay();
			printf("8\n");
		}
		// Check PD10 -> C3
		if (!(*pInputDataReg & (1 << 10))) {
			delay();
			printf("9\n");
		}

		// Make all rows high
		*pOutputDataReg |= (0x0f);
		// Make r4 low (PD3)
		*pOutputDataReg &= ~(1 << 3);

		// Scan the columns
		// Check PD8 -> C1
		if (!(*pInputDataReg & (1 << 8))) {
			delay();
			printf("*\n");
		}
		// Check PD9 -> C2
		if (!(*pInputDataReg & (1 << 9))) {
			delay();
			printf("0\n");
		}
		// Check PD10 -> C3
		if (!(*pInputDataReg & (1 << 10))) {
			delay();
			printf("#\n");
		}
	}
}
